### ISSUE TITLE
Specifying depends for multi-table inheritance

### ISSUE THREAD

**Issue by Iyochy** [netzkolchose/django-computedfields#123]
Hi,

my issue is with multi-table inheritance. I can't get inherited models to update automatically.

I have model A and B sucht that:

ComputedFieldsModel => A => B

I have a field called "info" in A which is a computed field and has only local dependencies on the model.
I have a field called "relationtoc" in A which is  a foreign key field to model C (see below)

I also have a model C with a computedfield, which specifies depends with ("relationtoc", ["info"]).

This works for autmatic updates of the computedfield on C as long as I save a model A, but as soon as I save a model B, the recalculation does not happen. 

Showdependencies lists the correct field with the correct dependencies but the update does not happen.

The documentation (https://django-computedfields.readthedocs.io/en/latest/manual.html#model-inheritance-support) specifies, that there is no automatic up or down casting as the field is always treated as a field on the final model in the inheritance chain. But "B" should qualify as the last model in the chain, no?

So my question is two-fold:

1. Is this supported at all and do I just need to specify depends in a certain way?
2. Would it be sufficient to call "update_dependent" on model C after saving model B ?

Thanks in advance for your time and thanks for the great software you are providing here. :)

kind regards,

Iyochy

**Comment by jerch** [comment]
@Iyochy Can you show me the model definitions (just a short version showing the critical paths)?

A few remarks to your questions:


> The documentation (https://django-computedfields.readthedocs.io/en/latest/manual.html#model-inheritance-support) specifies, that there is no automatic up or down casting as the field is always treated as a field on the final model in the inheritance chain. But "B" should qualify as the last model in the chain, no?

Ah maybe thats wrongly phrased in the docs - no up- or downcast here means, that the cf logic only kicks in for the exact instance, not any left or right instance of the model chain (thus also not for the last one, if the field was declared on an earlier one).

> So my question is two-fold:
> 
>     1. Is this supported at all and do I just need to specify depends in a certain way?

Yes, that is supported by the right `depends` entries, but you have to shape them manually. There is an example in the docs for it (see https://django-computedfields.readthedocs.io/en/latest/examples.html#neighboring-models). If you show me the model declaration, I might be able to help you here.

>     2. Would it be sufficient to call "update_dependent" on model C after saving model B ?

No, not unless you have the right `depends` entries set. What should work though is calling `update_dependent` on model A. Buts thats prolly not what you want. Background on this - cf completely depends on correct `depends` entries for its resolver to take action. Calling `update_dependent` on the other hand works two-fold: it always updates local fields (here A would get fixed from calling it on A), but also invokes the resolver to recalc all dep fields. The latter does not work yet due to missing the downcast depends entries (thus calling on C does not see A yet to be refreshed).

**Comment by Iyochy** [comment]
This is Model A:

```
class Proof(ComputedFieldsModel):

    ....
    purpose = models.ForeignKey(
        "PurposeAssignment",
        null=True,
        blank=True,
        related_name="proof_assignments",
        verbose_name=_("Proofs"),
        on_delete=models.CASCADE,
        editable=False,
    )

    ...

    start = models.DateField(
        _("Valid from"), null=True, blank=True, default=datetime.date.today
    )
    end = models.DateField(_("Valid until"), null=True, blank=True)

    @computed(
        models.CharField(
            _("Status"),
            max_length=2,
            choices=ProofStatus.choices(),
            default=ProofStatus.WAITING.value,
        ),
        depends=[("self", ["start", "end"])],
    )
    def status(self):
        ...
```

This is Model B:

```
class QualificationProof(Proof):
    ... some more local fields
```

This is Model C: (FK from model A points to it), this is a "through" model (m2m) if thats relevant:

```
class PurposeAssignment(ComputedFieldsModel):
    ...
    @computed(
        models.CharField(
            _("Qualification status"),
            max_length=2,
            null=True,
            choices=ProofStatus.choices(),
        ),
        depends=[("proof_assignments", ["status"])],
    )
    def qualification_status(self):
        ...
```

So you can see, that the computedfield on Model C points to a field on ModelA (which model B should have inherited), but if I call save on a Model A, a recalculation is triggered, but not if I call save on Model B.

Thanks again for your assistance. :)

Version 0.2.0 if thats relevant.

Also here is the dependency specification:

```
- appname.proof:
    status -> appname.purposeassignment [..., qualification_status, ....]
    status-> ...
```

**Comment by jerch** [comment]
Imho it should work, if you change `depends` on `PurposeAssignment` as follows:
```python
    @computed(
        models.CharField(
            _("Qualification status"),
            max_length=2,
            null=True,
            choices=ProofStatus.choices(),
        ),
        depends=[
            ("proof_assignments", ["status"]),
            ("proof_assignments.qualificationproof", ["status"]),
        ],
    )
    def qualification_status(self):
        ...
```

**Comment by Iyochy** [comment]
Awesome. Turns out there is a way to specify the model relation - and I was just not looking in the right spot in the documentation. My bad - sorry. 

This also gives some efficiency gains as I don't need to update the field anytime the non-specific model has been updates which is not significant for the computedfield. 

thanks alot! o/

I'm also based in germany, not in Jena though - but in NRW. If I can return the favour someday, hit mit up.

**Comment by jerch** [comment]
> This also gives some efficiency gains as I don't need to update the field anytime the non-specific model has been updates which is not significant for the computedfield.

Yes thats the whole idea behind the resolver, its tries very hard to not overly touch the db. This comes with a big downside - if you forgot a depends entry somewhere, things will not update properly anymore.
