### ISSUE TITLE
M2m through case

### ISSUE THREAD

**Issue by lsmith77** [netzkolchose/django-computedfields#139]
I am dealing with a slight variation of the M2M through example and I am running into the issue that if I use Django Admin (grapelli) to update the M2M relationship, I do not get the updated list on the initial save (only on a 2nd save without modification I get the actual list).

I am trying to use `depends` to solve this similar to the example on https://django-computedfields.readthedocs.io/en/latest/examples.html#m2m-relations but it doesn't seem to have any effect.

See my attempt below. Note I cannot `depends` on `rule_dimensions.dimension`, since there is no such field on the `Rule` class.

Essentially what I need to achieve is that the `self.dimensions.all()` returns the list after everything is else is saved. Any way to do this?

```
class Dimension(ComputedFieldsModel):
    name = models.CharField(max_length=32)

class Rule(models.Model):
    name = models.CharField(max_length=32)
    dimensions = models.ManyToManyField(Dimension, related_name='rule_dimensions', through='RuleDimension')

    @computed(models.JSONField(default=dict),
        depends=[
            ('dimension', ['name'])
        ],
        prefetch_related=['rule_dimensions']
    )
    def groupjoins(self):
        if not self.pk:
            return []

        names = []
        for dimension in self.dimensions.all():
            names.append(dimension.name)
        return names

class RuleDimension(models.Model):
    dimension = models.ForeignKey(Dimension, related_name='dimensions')
    rule = models.ForeignKey(Rule, related_name='rules')
```

**Comment by lsmith77** [comment]
OK figured it out

```
    @computed(
        models.JSONField(default=dict),
        depends=[
            ("dimensions", ["name"]),
            ("ruledimension", ["diversity_dimension"]),
        ],
        prefetch_related=["dimensions"],
    )
```

**Comment by jerch** [comment]
Hmm, this looks a bit change to me - following your initial description the approach with only `('dimension', ['name'])` should have worked in the first place. If you are using v0.2.4 - can you check if the simple `depends` with v0.2.3? Background: v0.2.4 contains a query optimization for M2M relations, there is a small chance a bug slipped through with that change.

Alternatively - can you post your models reduced to cf-relevant fields and your final computed field declaration? From there I can try to check if there is really a new issue with the latest changes.

**Comment by lsmith77** [comment]
yeah .. `dimensions` vs. `dimension` .. I tried to minimize my example and likely made a typo there.
