### ISSUE TITLE
Dependencies on backwards relation doesn't detect changing foreign key

### ISSUE THREAD

**Issue by olivierdalang** [netzkolchose/django-computedfields#14]
Hi !

I have a very common case where changing the parent of a child doesn't correctly update computed fields.

Cheers !

```python
# models.py
class Parent(ComputedFieldsModel):
    @computed(models.IntegerField(default=0), depends=['children#parent'])
    def children_count(self):
        return self.children.all().count()

class Child(ComputedFieldsModel):
    parent = models.ForeignKey(Parent, related_name='children', on_delete=models.CASCADE)

# tests.py
p1 = Parent.objects.create()
p2 = Parent.objects.create()
c1 = Child.objects.create(parent=p1)
c2 = Child.objects.create(parent=p2)

# One child per parent
p1.refresh_from_db()
p2.refresh_from_db()
self.assertEqual(p1.children_count, 1)
self.assertEqual(p2.children_count, 1)

# Move the child to another parent
c2.parent = p1
c2.save()

p1.refresh_from_db()
p2.refresh_from_db()
self.assertEqual(p1.children_count, 2)  # Fine
self.assertEqual(p2.children_count, 0)  # Assertion error : 1 != 0
```

**Comment by olivierdalang** [comment]
commit with the failing test implemented : https://github.com/olivierdalang/django-computedfields/commit/8f785796b211dce8f28012bf6cde1f2c960a58f3

**Comment by jerch** [comment]
Looks like a serious bug, not sure yet what causes it. Does it work if you dont set the reverse name explicitly?

**Comment by olivierdalang** [comment]
No it's the same (removed `related_name` and replaced `children` by `child_set`).

I guess what happens is that after save, there's no link between `c2` and `p2` anymore, so that it doesn't find the dependency.

We may need to keep initial values of relations somewhere in the instance, and check them too.

**Comment by jerch** [comment]
> I guess what happens is that after save, there's no link between c2 and p2 anymore, so that it doesn't find the dependency.
We may need to keep initial values of relations somewhere in the instance, and check them too.

Yes most likely. I had the same "artifact" during set deletions/changes on M2M fields, which required to save the old state before the action took place.

**Comment by olivierdalang** [comment]
I had a look at the code, and not exactly sure I understand everything, but indeed I think it requires adding some logic (probably in `__init__`) to store initial values in the for relations, and then adding them in `_querysets_for_update`.
That would work at instance level, and without much overhead I think ?

When updating in batch, I think it's not possible to do it automatically. So it would be about adding a clear warning in the docs and provide a way to supply pks of relations to refresh.

**Comment by jerch** [comment]
Yes, I guess we have to load the resolver map in `__init__` already and store initial values of depends fields, then we can compare them later on during `save` and trigger needed actions on old instances as well. Not sure yet if we get a problem with execution order here (whether the action takes place on the old or the new one first, the fact that the logic descends to all affected objects makes it abit hard to grasp).
So on individual instance level this should work, yeah.

I think the batch case is still doable, but needs another queryset function, that gets executed before doing the changes, and feeding the changeset back into `update_dependent`. Not sure yet, will see about that.

**Comment by jerch** [comment]
Geez, doing changes to `__init__` is toxic in a sense, that any model, that might occur in a depends relation chain needs to have the old value storage extension. This far only models containing computed fields need to be of the custom model type `ComputedFieldsModel`. Seems this needs a bit more thinking how to layout it without worse side effects by polluting a whole project with it.

**Comment by olivierdalang** [comment]
@jerch just to not to duplicate efforts, are you planning to work on this ? If not, I may give it a shot, but not sure when I'll have the time to (I'm not currently using django-computedfields, only planning of using it to replace a custom system)

**Comment by jerch** [comment]
@olivierdalang Will see if I can get my hands dirty on Monday, not sure if Ill come up with something usable yet, as it might change several internal things. I can push to a PR early, if you find some time, so you can step in, maybe with a simpler idea, whatsoever. This issue has the potential to get "viral" throughout the codebase, thus its better if more peeps keep an eye on it :smile:

**Comment by jerch** [comment]
@olivierdalang Plz see #15 for a first attempt.
