### ISSUE TITLE
Support for django>=5.0

### ISSUE THREAD

**Issue by MarcusFeldhans** [netzkolchose/django-computedfields#147]
--> _First and foremost, thanks for creating this project. It's been very helpful in all projects I've developed so far._ <--

I'm requesting support of this project for the latest django version 5.0.

With frequent security updates needed for django, the only safe version to use is 4.2.11 right now. This will likely change soon so upgrades to django>=5 are needed. I would like to keep this package going forward.

Thanks for your support!

**Comment by jerch** [comment]
Can you explain what you mean with django>=5.0? Currently all security patches in the 5.0 line should work out of the box, as security patches are not meant to change API details. Also `setup.py` list 'Django>=4.2,<5.1' as dependency for django, which should include everything under 5.0.x.

I cannot easily widen that version window to lets say <6, as django minor versions often include subtle API changes, which need explicit testing before announcing support for it. Means 5.1 already might contain an incompatible change and so on.

**Comment by MarcusFeldhans** [comment]
Hi @jerch,
thanks for your quick response. It seems that I've made a mistake when upgrading django-computedfields and it didn't pull the latest version while I believed it was the latest version -> 0.2.4 did complain about me trying to upgrade django.

After correctly upgrading this package to 0.2.5, everything worked again.

Sorry about that and thanks again for your support. Appreciate it.

**Comment by roniemartinez** [comment]
Django 5.1 was [released](https://docs.djangoproject.com/en/5.1/releases/5.1/) recently.

We currently cannot upgrade to Django 5.1 since the latest versions are pinned to max 5.0. Upgrading Django will downgrade django-computedfields to 0.1.7.

Can you please reopen and add support?

<img width="401" alt="image" src="https://github.com/user-attachments/assets/cc008f7f-c754-45a4-9867-5dd4408d77f0">
