### ISSUE TITLE
Newly dependent instance creating

### ISSUE THREAD

**Issue by Alex-Sichkar** [netzkolchose/django-computedfields#149]
Minimal example:

```Python
class Order(models.Model):
    @computed(
        models.DecimalField(max_digits=10, decimal_places=2, default=0),
        depends=[("items", ["quantity", "price"])],
    )
    def total_amount(self):
        if self._state.adding:
            return 0
        returm sum([item.total_price for item in self.items.all()], Decimal())

class OrderItem(models.Model):
    ...

````

When new OrderItem instance created, `Order.total_amount` is not recalculated. Am I doing something wrong?

**Comment by Alex-Sichkar** [comment]
`total_price` is just a property, not model field.

**Comment by jerch** [comment]
Can you create a minimal repro? This should work, thus I guess that there is something off with your models.

**Comment by Alex-Sichkar** [comment]
Yes, you are right, I found the reason. I just had to refresh the instance from the database. Closing...
