### ISSUE TITLE
issues with computed fields on same model

### ISSUE THREAD

**Issue by jerch** [netzkolchose/django-computedfields#20]
Currently it is not possible to declare a dependency to another computed field on the same model. This might lead to corrupted content of a second computed field, that depends on the other:

```python
class SomeModel(ComputedFieldsModel):
    name = models.CharField(...)

    @computed(...)
    def comp1(self):
        return self.name.upper()

    @computed(..., depends=[???])  # currently no way to declare dep to comp1
    def comp2(self):
        return '###' + self.comp1
```
~This example still works correct without explicit depends notion, if `comp2` is declared in the code after `comp1`, because `save` would eval `comp1` first and get the correct result for `comp2` afterwards. But if they were declared in the opposite order, `comp2` would be eval'ed with an outdated value of `comp1` leading to the wrong result.~ This is not reliable, see below.

Solution:
Implement a way to declare a dependency on a computed field of the same model, something like `depends=['self#comp1']`. Then `save` would have to reorder the evaluation of computed field results (which is again a graph problem with possible cycles). This might be serializable by doing partial instance saves.

Current workaround:
~*If you have a multiple computed fields on one model, that depend on each other, always declare them in dependency order. Thus if computed field b depends on computed field a, a must be declared first in the code.*~
*Currently it cannot be ensured, that computed fields depending on another computed field of the same model are calculated in the right order. Thus dont depend computed fields on other model local computed fields until this is fixed.*

**Comment by olivierdalang** [comment]
Hey! was coming here to report this exact issue.

The workaround is not always working when the setup is slightly more complex.

With the models below, I have undetermined results (test works 50% of the time and fails 50% of the time). It seems order of declaration is only used when the model is saved through a regular save(), not when updated through the dependency graph.

Cheers !

```python
class Parent(ComputedFieldsModel):
    enabled = models.BooleanField(default=False)

class Child(ComputedFieldsModel):
    parent = models.ForeignKey(Parent, null=True, related_name='children', on_delete=models.SET_NULL)

    @computed(models.BooleanField(default=False), depends=['parent#enabled'])
    def has_enabled_parent(self):
        return self.parent is not None and self.parent.enabled

    @computed(models.FloatField(default=0), depends=['parent#enabled'])
    def actual_value(self):
        return 1 if self.has_enabled_parent else 0

# tests.py
p = Parent.objects.create()
c = Child.objects.create(parent=p)

c.refresh_from_db()
self.assertEqual(c.has_enabled_parent, False)
self.assertEqual(c.actual_value, 0)

p.enabled = True
p.save()

c.refresh_from_db()
self.assertEqual(c.has_enabled_parent, True)
self.assertEqual(c.actual_value, 1)  # fails 50% of the time
```

**Comment by jerch** [comment]
@olivierdalang Well my statement above is wrong (checked the code again) - even the coding order is not always preserved, as the fields are not registered by an ordered dict, but just a normal dict, which gives no guarantees about key order.
Already started with a fix, but it will take some time, as it involves a new depends declaration (see comment in #11) and an MRO-like reordering of local computed methods.

**Comment by jerch** [comment]
@olivierdalang 
Made some progress in #23. With that PR your example above should work if rewritten as:
```python
class ParentSelf(ComputedFieldsModel):
    enabled = models.BooleanField(default=False)

class ChildSelf(ComputedFieldsModel):
    parent = models.ForeignKey(ParentSelf, null=True, related_name='children', on_delete=models.SET_NULL)

    @computed(models.BooleanField(default=False), depends=[['parent', ['enabled']]])
    def has_enabled_parent(self):
        return self.parent is not None and self.parent.enabled

    @computed(models.FloatField(default=0), depends=[['self', ['has_enabled_parent']]])
    def actual_value(self):
        return 1 if self.has_enabled_parent else 0
```

Note though, that `['parent#enabled']` ==> `['parent', ['enabled']]` would not be a sufficient replacement to describe deps of `actual_value`, as it kinda lied about the true source of the dependencies used to calculate it (and the underlying graph would not grasp the `has_enabled_parent` to `actual_value` dep). With the new PR it will be important to list all deps with their true source (here `['self', ['has_enabled_parent']]`).
