### ISSUE TITLE
Will this block accidental overwrite of the computedfield value?

### ISSUE THREAD

**Issue by simkimsia** [netzkolchose/django-computedfields#22]
is this explicitly blocked?

```python

m = MyModel()
m.computed_field = "illegal" # this should be prevented
m.save() # can also throw error here 

```

**Comment by jerch** [comment]
@simkimsia This is not blocked, but gets overwritten during save call by the methods return value.

Imho there is not good way to block this without overloading field types or turning `computed_field` into a property like thingy / getattribute overwrite (which somewhat defeats the purpose of being a fast attribute on the instance for querying speedup).

If you have a good idea, how to block this on code level without big perf sacrifices - im all ears.

**Comment by simkimsia** [comment]
> @simkimsia This is not blocked, but gets overwritten during save call by the methods return value.


well so long as there’s no way that a programmer can accidentally overwrite the value via application code (direct change via database doesn’t count) then I’m fine.

So is this the case?

Another related question is if I run `refresh_from_database` what happens?

**Comment by jerch** [comment]
> well so long as there’s no way that a programmer can accidentally overwrite the value via application code (direct change via database doesn’t count) then I’m fine.
So is this the case?

Yes, but with a catch (as always) - If you have multiple computed fields on one model, and they depend on each other,  the logic cannot resolve them in correct order yet (see #20). Thus a re-assigment on code level would manifest itself. Once #20 is solved this should not happen anymore.

> Another related question is if I run refresh_from_database what happens?

Nothing special, it simply loads the value, that is stored in the database as for any other field.

**Comment by simkimsia** [comment]
It’s good enough

I currently care abt base computed field for now. Not nested computed fields

Thank you for your detailed answer 🙏
