### ISSUE TITLE
dependencies for abstract computed fields are lost

### ISSUE THREAD

**Issue by jerch** [netzkolchose/django-computedfields#25]
During model construction computed fields are correctly forwarded, while the dependencies are lost in the later inherited concrete model.
Happens around these lines: https://github.com/netzkolchose/django-computedfields/blob/0ecf28144807296c0f3b1581f289a02944b44a1f/computedfields/models.py#L41-L57

@mobiware FYI.

**Comment by mobiware** [comment]
I thought we had this covered in the unit tests I added

**Comment by jerch** [comment]
I encountered it while doing the `self` rewrite in PR #23, the model `Concrete` cannot spot the deps to `self.a` and `self.b`. There is a chance that it might be related to my recent changes, will see.

**Comment by jerch** [comment]
@mobiware Did some debugging - for these models:
```python
class Abstract(ComputedFieldsModel):
    class Meta:
        abstract = True

    a = models.IntegerField(default=0)
    b = models.IntegerField(default=0)

    @computed(models.IntegerField(default=0), depends=[['self', ['a', 'b']]])
    def c(self):
        return self.a + self.b


class Concrete(Abstract):
    d = models.IntegerField(default=0)
```
the depends notion is stuck on the abstract base class:
```
Abstract {'c': [['self', ['a', 'b']]]}
Concrete {}
```
Imho the fix is pretty simple - we just need to forward the depends declaration as well. Gonna add a fix in PR #23 (need it anyway there to get the test passing).

**Comment by mobiware** [comment]
Great that you figured it out.
However I see you're changing the dependency syntax and in your example you're specifying a dependency on the same class.
Previously we didn't have to explicitly declare dependencies on the same model, did we ?
Is it now required ?

**Comment by jerch** [comment]
Yes the old syntax did not require it, but the new one does. I had to do this since the old syntax was way too underdetermined because of autoresolving of model local fields. It caused tons of headache for local computed fields that depend on other local computed fields. The new syntax is able to avoid the ambiguity with an MRO resolver. (Thats what #23 is about.)

**Comment by mobiware** [comment]
What will happen if we forget to include all `self` dependencies ?
for instance if we write this (`self.b` is missing from dependency list):
```
    @computed(models.IntegerField(default=0), depends=[['self', ['a']]])
    def c(self):
        return self.a + self.b
```

`c` won't get updated if we update `b` then `save()` the model object ?

**Comment by jerch** [comment]
That depends, whether you save the instance by `save()` or by `save(update_fields=['a'])`. If `update_fields` is left blank, all computed fields are re-eval'ed (pretty much like the old behavior), with `update_fields=['a']` the MRO will determine, if the changed fields have intersections with local computed fields and will update those as well in correct order.

**Comment by mobiware** [comment]
OK thanks for the explanation, good to know !
