### ISSUE TITLE
Depends syntax clarification

### ISSUE THREAD

**Issue by rosiecakes** [netzkolchose/django-computedfields#28]
Hello! Thank you very much for your work on this project. My console started producing warnings this morning which I understand was added in the latest release, but the differences are not clear to me. 

None of my models currently rely on the "depends_on" decorator option, they all just re-compute upon save(). Does the new release now require that you explicitly declare `depends=[['self', [something]]]`?

**Comment by jerch** [comment]
Well yes, the new syntax needs all fields to be listed, even local ones (those `self` entries). This was needed to resolve an old issue with computed field execution precedence. The old syntax cannot provide that bit of information, it is way underdetermined.

Currently there is a shim for the old syntax in place, that silently applies the new rules internally and gives this warning. To get the transition from old to new syntax working, I had to implement a few assumptions. One assumption is - "a computed field, which has no `depends` declaration, pulls all local concrete non relational fields as dependency".

Thus a declaration in the old syntax like
```python
@computed(Field(..))  # no depends
```
turns into
```python
@computed(Field(..), depends=[['self', ['a', 'b', '..']]])
```
for `a`, `b`, ... not being a foreign key, m2m or o2o like field on a model.

The shim is problematic on its own, as it might lead to wrong field additions causing cycles to pop up (well you cannot really build a well defined rule set from an ambiguous one). So it is best to do the transition manually.

If you really meant to express a computed field without any dependency - this is currently only possible by setting it to `depends=[]`, as `None` is taken by the shim, but will be re-added once the old syntax is gone.

If you have issues with the new syntax, just drop me a note.

**Comment by rosiecakes** [comment]
sounds good, thanks! wanted to make sure I got it right before adjusting everything 👍
