### ISSUE TITLE
Unwanted updates when outer field changed

### ISSUE THREAD

**Issue by makseq** [netzkolchose/django-computedfields#3]
I have two models (simplified): 

```
class Project(Model):
    a = IntegerField()
    n = IntegerField()

class Task(ComputedFieldsModel):
    project = ForeignKey('Project', related_name='tasks', 
                                       on_delete=models.CASCADE, null=True)

    @computed(models.BooleanField(), depends=['project#n'])
    def calc(self):
        return self.project.n
```

1. How to avoid unwanted updates when I change **project.a** field only and call project.save()? 

2. When I try to delete project I get an exception ObjectDoesNotExist. So, I rewrite my code to: 

```
    @computed(models.BooleanField(), depends=['project#n'])
    def calc(self):
        try:
            return self.project.n
        except ObjectDoesNotExist: 
            return 0
```

And it seems a little bit ugly. Is it any way to avoid delete signal in depends=['project#n']?

Thank you in advance!

**Comment by jerch** [comment]
1. If you know which fields were changed, you can call `save` with those fields only, e.g. `project.save(update_fields=['a'])`. This should avoid calling the dependency chain here, since `Task.calc` only depends on field 'n'. If you omit `update_fields` (which is the default) it will walk all dependency chains, since all values could have changed.

2. Hmm, have you tried without the `null=True` clause? You will definately need your "ugly" rewrite, if you want it to support `null` as fk value. Reason behind - whenever `Task` gets saved it will run the computed method (thus fail if `.project` is `null`). I dont see a way around it, maybe a shorter way to express it:
```python
    @computed(models.BooleanField(), depends=['project#n'])
    def calc(self):
        if self.project:
            return self.project.n
        return 0
```

**Comment by makseq** [comment]
1. I use automatic serializer for Project (class ProjectSerializer(ModelSerializer)) and it calls save without my control. So, I'm not able to pass update_fields inside of save().

2. Unfortunately I must use null=True... I've tested it without null - everything is ok with computed. But it leads to another bugs in my program :(

**Comment by jerch** [comment]
Yes I see `update_fields` hardly being used by other apps, a pity (its in django for a very long time). Would it help to be able to deregister the updates for that specific task and reregister them later on?

**Comment by makseq** [comment]
Can you make some examples of deregistering & reregistring?

**Comment by jerch** [comment]
Well something like this:
```python
# operate as normal with updates...
deregister_computed_updates()
# operate with updates
# do here some tasks that you know they wont touch fields any computed one depends on
# task....
register_computed_updates()
# operate as normal again...

**Comment by makseq** [comment]
I think it's not good solution, because it makes the "magic" of computed fields is useless :( I need to know where to call deregister/register. But I work in team and I want no one to have a headache when it needs to be done.

**Comment by makseq** [comment]
I think it will be great to check is project.n from depends=['project#n'] changed or not. Maybe you need to make advanced field to save the last 'project.n' value in the task and match it with real project.n.

**Comment by jerch** [comment]
Well if you have tons of data changes to submit in bulk, maybe rewrite your code to use bulk actions? They dont trigger the updates, which should run much faster. Instead you can call `update_dependent(changed_objs)` when you are done with it (thus the update logic runs only once).

**Comment by makseq** [comment]
Yes, I think update_dependent can be a good idea. I'll try it, thank you!

**Comment by jerch** [comment]
Your welcome, if this does not work for you I might need some more info about the actual use case.

**Comment by makseq** [comment]
Now I try to use update_fields to resolve my problem with unwanted updates.
So, I write something to check how it works: 

```
class Project(Model):
    a = IntegerField()
    n = IntegerField(
    def save():
        super(Project, self).save(update_fields=['a'])
```

and nothing happens. My computed field calc in Task is not calculated. 
if I change save to

```
    def save():
        super(Project, self).save()
```

everything is worked. 
What do you thing I miss?

**Comment by makseq** [comment]
Sorry, but are you here?

**Comment by jerch** [comment]
@makseq Have you derived your class from `ComputedFieldsModel`?

**Comment by makseq** [comment]
You mean Task or Project?

**Comment by makseq** [comment]
Task is derived, yes.

**Comment by jerch** [comment]
Can you give me a correct stub of both classes and what is working/not working? Maybe there is something wrong or missing in the inheritance chain, no clue yet.

**Comment by makseq** [comment]
I'll try to simplify my code: 

```
class Project(Model):
    a = IntegerField()
    n = IntegerField()

    def save(): 
        update_fields = ['a']

        # we want to save self.n if it's changed only
        if self.__n != self.n:
            self.__n = self.n
            update_fields += ['n']

        print(update_fields)
        super(Project, self).save(update_fields=update_fields)


class Task(ComputedFieldsModel):
    project = ForeignKey('Project', related_name='tasks', on_delete=models.CASCADE, null=True)

    @computed(models.BooleanField(), depends=['project#n'])
    def calc(self):
        return self.project.n
```

I pass update_fields at this line: `super(Project, self).save(update_fields=update_fields)`. 
1. I change 'a' only, no 'n' affected
2. I do project.save()
3. I see that all the tasks recompute again :(

**Comment by jerch** [comment]
Thx for the example. I cannot quite repro your issue (your save method isnt even a valid method), still there seems to be a bug in https://github.com/netzkolchose/django-computedfields/blob/11128c1445a2dba77bbb24e4cdd65489772c633d/computedfields/models.py#L100

which prevents the update from being triggered if a single update field is given. Need to test this and track it further down.

**Comment by jerch** [comment]
The partial update with `update_fields` does not work currently if the field is a normal field, the update tree does only track individual fields if they are computed fields itself. Currently setting `update_fields` for non computed fields will completely omit updates in dependent fields, which is faulty behavior.

I remember that I had this implemented for normal fields in an earlier version, but removed it as all default actions always do a full `.save()` in django. Since `updated_fields` is documented API this should be readded to keep the dependent fields in sync.

**Comment by makseq** [comment]
Thank you a lot! I'll try to do it as I can.

**Comment by jerch** [comment]
Autoclosed by PR, reopen it so I can get your feedback.

**Comment by jerch** [comment]
@makseq: Does it work for you after the patch?

**Comment by makseq** [comment]
I just checked it today. Unfortunately. it doesn't work in my case. Sorry, but we decided to refuse computed fields in favor of django signals.
