### ISSUE TITLE
How to depend on manytoonerel

### ISSUE THREAD

**Issue by thht** [netzkolchose/django-computedfields#33]
hi,
let's say i have two models:
```python
class Registration(models.Model):
    @computed(FloatField(), depends=[['self', ['payment_set']]])
    def total_amount(self):
        paid = 0
        for cur_payment in self.payment_set.all():
            paid += cur_payment.amount

        return paid

class Payment(models.Model):
    amount = FloatField()
    registration = ForeignKey(Registration)
```

The expected behavior is that when a `Payment` gets is created with `registration` pointing to a specific instance of `Registration`, the `total_amount` field gets updated.

This used to work fine with the old depends syntax: `depends=['payment_set']`. But using the new one, i get the following exception:

```
django.core.exceptions.FieldDoesNotExist: Registration has no field named 'payment_set'
```

I also tried putting using a syntax like: `depends=[['payment_set', ['id']]]` without success. In that case, I do not get an error but the field won't update...

What am I doing wrong?

Thanks a lot!
Thomas

**Comment by jerch** [comment]
True, the new depends syntax is way stricter here with the fields:
- non-concrete fields can only be put on the left side (in relations)
- missing a field on the right side as data source will lead to missing updates, as the resolver does aggressive optimization

While the old syntax was easier in this regard, it also was ambigious and not able to re-eval multiple local computed fields in the right order. To solve that, I had to make the fields explicit.

In your case `[['payment_set', ['amount']]]` should work (note that you add from that field). Also `['self', ['payment_set']]` is not needed with that rule, as the resolver automatically expands on relational fields. Guess I need to add a few examples with common cases?

**Comment by thht** [comment]
ok, thanks for the help. and yes, more detailed documentation including some examples would be really helpful!

besides, i realized that my main issue was that updates because of dependencies do not trigger calling the `save` method of a model anymore... but i solved that as well....

thanks again!

**Comment by jerch** [comment]
@thht There is actually still a bug hidden, the autoexpand of `[['payment_set', ['amount']]]` to `[['payment_set', ['amount', 'registration']]]` currently does not work. Bug: #34
