### ISSUE TITLE
Support for django 3.0+

### ISSUE THREAD

**Issue by olivierdalang** [netzkolchose/django-computedfields#5]
The title says it all :-)

**Comment by jerch** [comment]
Thx for the reminder :heart: 

Did not get into contact with django 3 yet, from reading the changelog I dont expect major incompatibilities. Needs proper testing though.

**Comment by olivierdalang** [comment]
I'm just testing and about to open a PR

**Comment by jerch** [comment]
Sweet :+1:

**Comment by olivierdalang** [comment]
#6 (didn't run tests locally, but from quick testing it seems to work)

**Comment by olivierdalang** [comment]
@jerch Ok I think #6 is ready to be reviewed.
