### ISSUE TITLE
How to write computedfield that depends on the child model?

### ISSUE THREAD

**Issue by simkimsia** [netzkolchose/django-computedfields#60]
I have a model called WBS and it is the foreignkey to WBSLineItem

In WBSLineItem it has a booleanfield called is_used.

I like to have a similar field in WBS which is also boolean and also called `is_used`.

As long as any one of the WBSLineItem `is_used` is True, so is the parent WBS `is_used` is also True.

The examples seem to cover computed from the parent model instead of the child model

**Comment by jerch** [comment]
@simkimsia Can you show some example code? Problem here is what is meant by parent/child (FK relation? multi table inheritance? Something else?)

**Comment by simkimsia** [comment]
```python
class WBS(models.Model):
   is_used = ...

class WBSLineItem(models.Model):
   is_used=models.BooleanField(default=False)
  parent_wbs = models.ForeignKey(WBS, on_delete=models.CASCADE)
```

**Comment by jerch** [comment]
So `WBS.is_used` shall be computed based on `WBSLineItem.is_used`, this would work:
```python
@computed(BooleanField(), depends=['wbslineitem_set', ['is_used']])
def is_used(self):
  return any(list(self.wbslineitem_set.all().values_list('is_used', flat=True)))
```

The "aggregation" is subpar, and could be optimized by something like `Sum` on the boolean value, if the DBMS supports adding on boolean fields. Then the result would be 0 => False vs. !0 => True.

**Comment by simkimsia** [comment]
> if the DBMS supports adding on boolean fields. Then the result would be 0 => False vs. !0 => True.

I'm sorry can you elaborate on this? and how do I test? can i simply try

```sql
SELECT SUM(boolean_field) from wbslineitem_table where wbs_id = the_parent_id;
```

to prove/disprove this?

**Comment by jerch** [comment]
@simkimsia Yes you should be able to test that on the DBMS shell this way.

But my thinking is way too complicated still, easier should be to just filter on that field and eval the count:
```python
return True if self.wbslineitem_set.filter(is_used=True).count() else False
```
This should work on any db backend and avoids the costly value aggregation.

**Comment by simkimsia** [comment]
THank you I tried your code but I got this when i tried to run `python manage.py shell`

```sh
File "/usr/local/lib/python3.7/site-packages/computedfields/graph.py", line 474, in resolve_dependencies
    for path, fieldnames in depends:
ValueError: too many values to unpack (expected 2)
```

**Comment by simkimsia** [comment]
Oh by the way, I have to change your code to make it work for django 2.2

```python
@computed(
   models.BooleanField(default=False), depends=["wbslineitem_set", ["is_used"]]
)
def is_used(self):
     return True if self. wbslineitem_set.filter(is_used=True).count() else False
```

**Comment by simkimsia** [comment]
## UPDATE

Oh I think i know why. I was missing a pair of `[]`

so the code that finally worked is

```python
@computed(
        models.BooleanField(default=False), depends=[["actualresourcelinkage_set", ["is_used"]]]
    )
    def is_used(self):
        return True if self.actualresourcelinkage_set.filter(is_used=True).count() else False
```

Maybe you want to add an exception that catches this and then a somewhat developer friendly message?
