### ISSUE TITLE
[Question] use pydantic to check for the depends?

### ISSUE THREAD

**Issue by simkimsia** [netzkolchose/django-computedfields#62]
from my experience in this comment https://github.com/netzkolchose/django-computedfields/issues/60#issuecomment-671192520

I think would be good to add a more illuminating error message to notify the developer they not using preparing the depends properly. 

Maybe use something like pydantic or some other validation to make sure that the it's a list of list/tuples and then inform the developer accordingly

What do you think?

**Comment by jerch** [comment]
Yes, thats prolly a good idea. Is `pydantic` any good? Never used it.

Also I am trying to keep the module as third party free as possible - so maybe a simple own written checker would do? Wonder if we could reuse django's validation classes here to some extend.

**Comment by jerch** [comment]
Thinking again about this - imho the optional type system be enough here to give users hints, how to properly interact with `django-computedfields` and populate the `depends` keyword. On the side of supported python versions we should be safe to use this with the older syntax (not yet supporting the newer easier union stuff).

@simkimsia What do you think - would proper API typing give enough explanation the users during coding? `pydantic` looks like a heavy runtime lifting compared to the typing system, thus I hestitate to add anything like that.

**Comment by simkimsia** [comment]
Coincidentally I also now think pydantic is pretty heavy

So it's best it's a all or nothing when it comes to pydantic. Either go all in on it or not at all

Is not a bad thing and I admire what pydantic is doing but for that reason I also withdraw my Original idea of it combining with computedfields

**Comment by simkimsia** [comment]
Ya I don't know enough abt the api typing to comment on that

Perhaps you can take the original inciting incident and use that to demo an example?

**Comment by jerch** [comment]
Thx for your quick reply. Will see if I get a satisfying result with typing annotation alone with your incident.

**Comment by jerch** [comment]
After playing with type hints for many hour it seems not to be a very reliable help yet for django projects (main reason being changed type annotations in django-stubs, which are incompatible to certain low-level actions in resolver.py, which gives more false alerts than it helps in the end). The whole type hint story in python still feel like an ugly patch on top of a dynamic language, esp. for things like django, where a lot of magic is going on underneath.

Prolly will end up doing some manual basic runtime sanity checks in early bootstrap phase...

**Comment by simkimsia** [comment]
I'm also okay with that. What I really need is an example that shows me how to use to solve my inciting incident or at least early detect

**Comment by jerch** [comment]
Well I am getting the correct types inferred with type hints if I do it very explicit:
```python
from django.db import models
from computedfields.models import ComputedFieldsModel, computed

# without type annotation
class MyModel(ComputedFieldsModel):
    name = models.CharField(max_length=32)  # auto-typed as models.CharField[Unknown, Unknown]

    @computed(
        models.CharField(max_length=32),
        depends=[
            ('self', ['name'])
        ]
    )
    def upper_name(self):
        return self.name.upper()

    @computed(
        models.CharField(max_length=32),
        depends=[
            ('self', ['upper_name'])
        ]
    )
    def comp2(self):
        return self.upper_name + 'xy'

# vs. with explicit type annotation
from typing import cast

class MyModel(ComputedFieldsModel):
    name: models.CharField[str, str] = models.CharField(max_length=32)

    @computed(
        cast(models.CharField[str, str], models.CharField(max_length=32)),
        depends=[
            ('self', ['name'])
        ]
    )
    def upper_name(self) -> str:  # rtype can be inferred if `.name` is fully typed
        return self.name.upper()

    @computed(
        cast(models.CharField[str, str], models.CharField(max_length=32)),
        depends=[
            ('self', ['upper_name'])
        ]
    )
    def comp2(self) -> str:  # rtype can be inferred, if `.upper_name` is properly typed
        return self.upper_name + 'xy'

```
That way both PyCharm and vscode (PyLance) can successfully derive the types of `inst.upper_name` and `inst.comp2`. It even works across multiple cf dependencies, it pulls the field types correctly across the computed decorators.

But what really bothers me - why do I have to type fields that explicitly in the first place? This gets really annoying, esp. with those casts in the arguments of `@computed`. Maybe I am using it wrong, or this is an issue with django-stubs. If I skip the explicit typing the fields only get announced as `models.CharField[Unknown, Unknown]`, and all follow-up inferred types switch to `Unknown`. Ideally a standard model field declaration already contains the right get and set values, no clue why thats not the case for me.

**Comment by jerch** [comment]
So my idea currently is:
- do some manual basic runtime checks (beside those already in place, like the path descent/left side and existance of concrete fields/right side already gets checked)
- provide some pyi files with typings for the top level API once I figured out the low level issues with django-stubs

**Comment by simkimsia** [comment]
Thanks for update

Do what works for you as maintainer

I'll be happy to try new features when they are done

**Comment by jerch** [comment]
@simkimsia Would such an explanatory exception be enough, or is that even too verbose?

```python
    raise ResolverException(MALFORMED_DEPENDS)
computedfields.resolver.ResolverException: 
Your depends keyword argument is malformed.

The depends keyword should either be None, an empty listing or
a listing of rules as depends=[rule1, rule2, .. ruleN].

A rule is formed as ('relation.path', ['list', 'of', 'fieldnames']).
The relation path either contains 'self' for fieldnames on the same model,
or a string as 'a.b.c', where 'a' is a relation on the current model
descending over 'b' to 'c' to pull fieldnames from 'c'. The denoted fieldnames
must be concrete fields on the rightmost model of the relation path.

Example:
depends=[
    ('self', ['name', 'status']),
    ('parent.color', ['value'])
]
This has 2 path rules - one for fields 'name' and 'status' on the same model,
and one to a field 'value' on a foreign model behind 'color',
that is accessible from the current model through a parent -> color relation.
```

**Comment by simkimsia** [comment]
Sorry 😞 I forgot to get back to you

It's a bit verbose but I think is good enough 

Thanks for doing this 🙇🏻‍♂️

**Comment by simkimsia** [comment]
> Also added type hints with #86. If you want to test that, it currently works in vscode and plain mypy. 

oh nice i use vscode :)
