### ISSUE TITLE
Compute newly added field to a model

### ISSUE THREAD

**Issue by StriveForBest** [netzkolchose/django-computedfields#63]
I added a new computed field to my `Work` model which pulls the description from self -> reverse_fk/m2m -> fk:

```python
@computed(
    models.CharField(max_length=32, default='', blank=True),
    depends=[['_statuses', ['status_type']],],
    prefetch_related=['_statuses']
)
def current_status(self):
    if not self.pk:
        return ''
    return self.get_current_status().status_type.description
```

**First question:** Will i benefit from `prefetch_related` here at all?

Now I need to calculate and store it. I wrote a migration that runs the following code:

```python
def resync_work_current_status(apps, schema_editor):
    Work = apps.get_model('works', 'Work')
    update_dependent(Work.objects.all(), update_fields=['current_status'])
```

**Second question:** The migration executes very quick and has no effect, why is that? Should I import a model from the project instead of `apps.get_model()` to use with `django-computedfields`?

Finally, running from django shell:

```python
from computedfields.models import update_dependent
update_dependent(Work.objects.filter(current_status=''), update_fields=['current_status'])
```

**Third question:** This runs forever and I don't know if it's doing anything. I have 71759 instances.

**Comment by jerch** [comment]
@StriveForBest 

**First question:**
Can you show the code of `self.get_current_status()`? Without it I cannot tell you, if the computed field is properly set up or if `prefetch_related` would be of any help.

**Second question:**
As answered in the other issue, `update_dependent` cannot be used from migrations currently (will literally do nothing). Currently `update_dependent` has to be called from a proper loaded full django state with model classes loaded. What should work - create a `RunPython` scriptlet, that does that as last action from a migration.

**Third question:**
Following your self -> reverse_fk/m2m -> fk notion above, this sounds reasonable, yes. The culprit is prolly the m2m relation in between, they tend to explode the update needs and should be used with great care only. I might be able to give you some ideas how to get around that, if you want to share the model specs. And yes, here using `prefetch_related` rules is typically a good idea, but depends alot on the real field indirections and how they gonna be used later on.

**Comment by StriveForBest** [comment]
> @StriveForBest
> 
> **First question:**
> Can you show the code of `self.get_current_status()`? Without it I cannot tell you, if the computed field is properly set up or if `prefetch_related` would be of any help.

It's a lot of code, ultimately it returns a queryset and then grabs the `.first()`. The question is mostly whether I benefit from using `prefetch_related` for the current db architecture.

There are 3 models:

```python
class Work(models.Model):
    title = models.TextField(db_column='Title', verbose_name='Title')


class WorkStatus(models.Model):
    work = models.ForeignKey('Work', models.CASCADE, related_name='_statuses')
    status_type = models.ForeignKey('WorkStatusType', models.PROTECT)


class WorkStatusType(models.Model):
    description = models.CharField(unique=True, max_length=50)
```

The computed field on the `Work` pulls the latest `WorkStatus` object for the work and grabs its `status_type.description`.

Is this enough information for you to help answer my question?

> 
> **Second question:**
> As answered in the other issue, `update_dependent` cannot be used from migrations currently (will literally do nothing). Currently `update_dependent` has to be called from a proper full django state with model classes loaded. What should work - create a `RunPython` scriptlet, that does that as last action from a migration.

Understood about the migrations. So if I am using `migrations.RunPython()`, what should it run? I tried calling management command `updatedata` from the migration, that also does nothing. Can you clarify what you mean?

> 
> **Third question:**
> Following your self -> reverse_fk/m2m -> fk notion above, this sounds reasonable, yes. The culprit is prolly the m2m relation in between, they tend to explode the update needs and should be used with great care only. I might be able to give you some ideas how to get around that, if you want to share the model specs. And yes, here using `prefetch_related` rules is typically a good idea, but depends alot on the real field indirections and how they gonna be used later on.

Thanks, so it seems like it's fine?

**Comment by jerch** [comment]
Now with parts of your model spec, I think the depends field and the prefetch rule should look like this:

```python
@computed(
        models.CharField(max_length=32, default='', blank=True),
        depends=[
            ['_statuses.status_type', ['description']]
        ],
        prefetch_related=['_statuses__status_type']
    )
    def current_status(self):
        ...
```

Note that the resolver auto expands interim models of relational paths (adds fk fields). On the right side of `depends` should be listed concrete db fields, that may alter the function result somehow. Thats important, otherwise field changes might not update all affected entries, example:

```python
class MyModel(ComputedFieldsModel):
    a = models.ForeignKey(A)
    b = models.ForeignKey(B)
    
    @computed(models.Field(...),
        depends=[
            ['a', ['some_field']],
            ['b', ['some_boolean_field']],   # this is important
        ]
    )
    def fetch_from_a(self):
        if b.some_boolean_field:
            return modify(a.some_field)
        return a.some_field
```

The example above shows a dep of the function result to `b.some_boolean_field`, therefore that field has to end up in `depends`, otherwise changes to `B.some_boolean_field` would never update `fetch_from_a` fields on related `MyModel` instances. (I write this, as it might apply to your lengthy `get_current_status()` call.

**Comment by StriveForBest** [comment]
> Now with parts of your model spec, I think the depends field and the prefetch rule should look like this:
> 
> ```python
> @computed(
>         models.CharField(max_length=32, default='', blank=True),
>         depends=[
>             ['_statuses.status_type', ['description']]
>         ],
>         prefetch_related=['_statuses__status_type']
>     )
>     def current_status(self):
>         ...
> ```
> 
> Note that the resolver auto expands interim models of relational paths (adds fk fields). On the right side of `depends` should be listed concrete db fields, that may alter the function result somehow. Thats important, otherwise field changes might not update all affected entries, example:
> 
> ```python
> class MyModel(ComputedFieldsModel):
>     a = models.ForeignKey(A)
>     b = models.ForeignKey(B)
>     
>     @computed(models.Field(...),
>         depends=[
>             ['a', ['some_field']],
>             ['b', ['some_boolean_field']],   # this is important
>         ]
>     )
>     def fetch_from_a(self):
>         if b.some_boolean_field:
>             return modify(a.some_field)
>         return a.some_field
> ```
> 
> The example above shows a dep of the function result to `b.some_boolean_field`, therefore that field has to end up in `depends`, otherwise changes to `B.some_boolean_field` would never update `fetch_from_a` fields on related `MyModel` instances. (I write this, as it might apply to your lengthy `get_current_status()` call.


So, the thing is `WorkStatusType.description` probably won't ever change. It really should be a _ChoiceField_ but I inherited this legacy codebase and not allowed to change that. What will change is the addition of `WorkStatus` to `Work`. Whenever the new `WorkStatus` gets created for `Work` is when we need to recompute the field. Any guidance here? _concrete_ fields don't really change in this situation, just fk/m2m.


> > Understood about the migrations. So if I am using migrations.RunPython(), what should it run? I tried calling management command updatedata from the migration, that also does nothing. Can you clarify what you mean?
> 
> Imho the `call_command` invocation will not spawn a full django env. `RunPython` can do that (e.g. write a small python script, that calls the full django setup, and then calls `update_dependent(...)`).


So in the migration, write a function that calls the full django setup and then call it in `migrations.RunPython`? What do you mean by "full django setup"?


> > Thanks, so it seems like it's fine?
> 
> Almost, see my changes to the declaration above.

**Comment by jerch** [comment]
> So, the thing is WorkStatusType.description probably won't ever change. It really should be a ChoiceField but I inherited this legacy codebase and not allowed to change that. ... concrete fields don't really change in this situation, just fk/m2m.

Well if the concrete fields behind never change, then it might be ok to just deal with fk fields on the right side, yet I dont see a reason, why to take the risky path (the resolver will act the same but with less update rules, a rule that never gets triggered doesn't hurt either).

> What will change is the addition of WorkStatus to Work. Whenever the new WorkStatus gets created for Work is when we need to recompute the field. Any guidance here?

Thats an important piece of information (at least for proper prefetch optimizations) - so the main update pressure will come from `WorkStatus` updates later on? Now the question is - will that be 1-case updates (always incoming as single updates) or n-case updates (batched in bigger slices)?

> So in the migration, write a function that calls the full django setup and then call it in migrations.RunPython? What do you mean by "full django setup"?

With "full django setup" I mean a python script, that fuly bootstraps into django, e.g does something like this at the top:

```python
import django
os.environ['DJANGO_SETTINGS_MODULE'] = 'your_settings'
django.setup()
...
# maybe then this
for model in affected_models:
    update_dependent(model.objects.all())
```

**Comment by StriveForBest** [comment]
> > So, the thing is WorkStatusType.description probably won't ever change. It really should be a ChoiceField but I inherited this legacy codebase and not allowed to change that. ... concrete fields don't really change in this situation, just fk/m2m.
> 
> Well if the concrete fields behind never change, then it might be ok to just deal with fk fields on the right side, yet I dont see a reason, why to take the risky path (the resolver will act the same but with less update rules, a rule that never gets triggered doesn't hurt either).

That is true, would this work then?
```python
@computed(
        models.CharField(max_length=32, default='', blank=True),
        depends=[
            ['_statuses', ['status_type']],
            ['_statuses.status_type', ['description']]
        ],
        prefetch_related=['_statuses__status_type'],
    )
    def current_status(self):
        if not self.pk:
            return ''
        return self.get_current_status().status_type.description
```

> > What will change is the addition of WorkStatus to Work. Whenever the new WorkStatus gets created for Work is when we need to recompute the field. Any guidance here?
> 
> Thats an important piece of information (at least for proper prefetch optimizations) - so the main update pressure will come from `WorkStatus` updates later on? Now the question is - will that be 1-case updates (always incoming as single updates) or n-case updates (batched in bigger slices)?

Yes, the field needs to be re-computed every time a new `WorkStatus` for the work is created or changed/saved.
They will always be a 1-case update (I think), there is an API endpoint to update the status on Work, which really just creates a new single `WorkStatus` object.


> > So in the migration, write a function that calls the full django setup and then call it in migrations.RunPython? What do you mean by "full django setup"?
> 
> With "full django setup" I mean a python script, that fully bootstraps into django, e.g does something like this at the top:
> 
> ```python
> import django
> os.environ['DJANGO_SETTINGS_MODULE'] = 'your_settings'
> django.setup()
> ...
> # maybe then this
> for model in affected_models:
>     update_dependent(model.objects.all())
> ```

Is it okay to do this in the migration's function?  I am using `django-configurations`, so the setup script lives in a different place, but pretty much this:
```python
# Generated by Django 3.1.1 on 2020-09-23 20:15
import configurations

from computedfields.models import update_dependent
from django.db import migrations

from gagosian.works.models import Work


def compute_denormalized_work_fields(apps, schema_editor):
    configurations.setup()
    update_dependent(Work.objects.all())


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0119_work_current_status'),
    ]

    operations = [
        migrations.RunPython(compute_denormalized_work_fields, migrations.RunPython.noop)
    ]

```

**Comment by jerch** [comment]
> That is true, would this work then? [code ...]

Yes that should work. The `['_statuses', ['status_type']]` is superfluous, but does not hurt either.

> Yes, the field needs to be re-computed every time a new WorkStatus for the work is created or changed/saved.
They will always be a 1-case update (I think), there is an API endpoint to update the status on Work, which really just creates a new single WorkStatus object.

Ok, imho the best you can get here is with a `['_statuses__status_type']` prefetch rule. Note that during creation this will not help at all, as a newly created and not yet saved model instance cannot make use of queryset methods (the db has nothing to do query opts with yet). Both `select_related` and `prefetch_related` rule will only apply for later updates of computed fields, never for inserts. If you already have issues on during inserts, then your method code simply takes too long for whatever reason (maybe check for proper indices on fields?)

> Is it okay to do this in the migration's function? I am using django-configurations, so the setup script lives in a different place, but pretty much this: ...  I shouldn't be using apps.get_model('works', 'Work'), direct import is what I need?

No clue about `django-configurations` and whether they spawn a fully django in the background. A safe bet with `RunPython` would be to use it as hook to a completely independent python script (e.g. call `Popen` with the script). Or just call `manage.py updatedata` after your `manage.py migrate` (easy way).

**Comment by StriveForBest** [comment]
> > That is true, would this work then? [code ...]
> 
> Yes that should work. The `['_statuses', ['status_type']]` is superfluous, but does not hurt either.

Thanks!

> > Yes, the field needs to be re-computed every time a new WorkStatus for the work is created or changed/saved.
> > They will always be a 1-case update (I think), there is an API endpoint to update the status on Work, which really just creates a new single WorkStatus object.
> 
> Ok, imho the best you can get here is with a `['_statuses__status_type']` prefetch rule. Note that during creation this will not help at all, as a newly created and not yet saved model instance cannot make use of queryset methods (the db has nothing to do query joins/opts with yet). Both `select_related` and `prefetch_related` rule will only apply for later updates of computed fields, never for inserts. If you already have issues during inserts, then your method code simply takes too long for whatever reason (maybe check for proper indices on fields?)

I simplified the code, this should work, thank you!

> > Is it okay to do this in the migration's function? I am using django-configurations, so the setup script lives in a different place, but pretty much this: ...  I shouldn't be using apps.get_model('works', 'Work'), direct import is what I need?
> 
> No clue about `django-configurations` and whether they spawn a full django in the background. A safe bet with `RunPython` would be to use it as hook to a completely independent python script (e.g. call `Popen` with the script). Or just call `manage.py updatedata` after your `manage.py migrate` (easy way).

I'll just call the management command after the migrations. It would be great if you had a verbosity flag to have your management command output something to see the progress.


Another issue I am running into is when I delete a `Work` it cascade deletes the related `WorkStatus` and (not sure why) tries to re-calculate the computed field. Is there a way to not have the lib do that? It makes no sense as the instance is being deleted anyway. Currently, the hackish workaround I implemented is checking if related m2ms exist like this:

```python
@computed(
        models.CharField(max_length=32, default='', blank=True),
        depends=[
            ['_statuses', ['status_type']],
            ['_statuses.status_type', ['description']],
        ],
        prefetch_related=['_statuses__status_type'],
    )
    def current_status(self):
        """
        Computed field that stores most recent status description for work.
        """
        if not self.pk or not self._statuses.exists():
            return ''
        return self._statuses.first().status_type.description
```

I am not sure at all, why the library is doing it. I suspect it's doing it on pre_delete or post_delete.

**Comment by jerch** [comment]
> I'll just call the management command after the migrations. It would be great if you had a verbosity flag to have your management command output something to see the progress.

Yeah the management command is still abit thin codewise. A verbose flag would certainly help, not sure yet how to get something like a real progress running there, as the resolver walks a model tree with unknown affected entries (it calculates the entries just right before entering the model). Maybe a dry-run could collect that data beforehand, have to see about the performance implications. (Also see #32).

> Another issue I am running into is when I delete a Work it cascade deletes the related WorkStatus and (not sure why) tries to re-calculate the computed field.

Hmm, I think that is caused by `.first()` which will raise if the related manager provides no results. But that would be caused by deleting the only `WorkStatus` item, not a `Work` item, weird (given the computed field is on `Work`). Can you create a shortened version to repro it? From what you wrote above I see no reason, why the resolver would try to update a computed field of a record that just got deleted. You might have triggered some weird delete cascading here, still that should not happen (django itself puts delete cascades under transactions, thus the resolver should not even see the wonky intermediate state). There is a serious bug hidden, if that happens.

**Comment by StriveForBest** [comment]
> > I'll just call the management command after the migrations. It would be great if you had a verbosity flag to have your management command output something to see the progress.
> 
> Yeah the management command is still abit thin codewise. A verbose flag would certainly help, not sure yet how to get something like a real progress running there, as the resolver walks a model tree with unknown affected entries (it calculates the entries just right before entering the model). Maybe a dry-run could collect that data beforehand, have to see about the performance implications. (Also see #32).

I think one of the more verbose output options could be a simple stdout of (Updating 1/X Model instance) as you're looping through them anyway. dry-run would be amazing too!
 
> > Another issue I am running into is when I delete a Work it cascade deletes the related WorkStatus and (not sure why) tries to re-calculate the computed field.
> 
> Hmm, I think that is caused by `.first()` which will raise if the related manager provides no results. But that would be caused by deleting the only `WorkStatus` item, not a `Work` item, weird (given the computed field is on `Work`). Can you create a shortened version to repro it? From what you wrote above I see no reason, why the resolver would try to update a computed field of a record that just got deleted. You might have triggered some weird delete cascading here, still that should not happen (django itself puts delete cascades under transactions, thus the resolver should not even see the wonky intermediate state). There is a serious bug hidden, if that happens.

It's not the `.first()`. So my code is this:
```python
return self._statuses.first().status_type.description
```
It fails with error `AttributeError: NoneType has no attribute status_type` because `self._statuses.first()` returns None as all of the statuses are deleted at this point.
the resolver tries to execute my computed field logic on delete, `WorkStatus` to `Work` FK has `on_delete=models.CASCADE` so i suppose it happens when it deletes `WorkStatus` objects. I also `ipdb`ed in my computed field code and could confirm my `Work/self` still has id, meaning its' not a `post_delete` on `Work`.
I added a print statement in my `current_status` computed field method. Here is a code snippet that reproduces the issue.
```python
In [1]: w = Work.objects.get(id=163869)

In [2]: w.statuses.all()
Out[2]: <QuerySet [<WorkStatus: Sold>, <WorkStatus: Available>, <WorkStatus: Sold>]>

In [3]: w.delete()
recomputing current_status
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-8b0d138c35df> in <module>
----> 1 w.delete()

~/projects/gagosian/noya/gagosian/works/models.py in delete(self, **kwargs)
   1002         # PHP also removes this work from scratchpads, which we do not use.
   1003
-> 1004         super().delete(**kwargs)
   1005
   1006

~/venv/noya-TS4FQGPC/lib/python3.7/site-packages/django/db/models/base.py in delete(self, using, keep_parents)
    945         collector = Collector(using=using)
    946         collector.collect([self], keep_parents=keep_parents)
--> 947         return collector.delete()
    948
    949     delete.alters_data = True

~/venv/noya-TS4FQGPC/lib/python3.7/site-packages/django/db/models/deletion.py in delete(self)
    434                     for obj in instances:
    435                         signals.post_delete.send(
--> 436                             sender=model, instance=obj, using=self.using
    437                         )
    438

~/venv/noya-TS4FQGPC/lib/python3.7/site-packages/django/dispatch/dispatcher.py in send(self, sender, **named)
    177         return [
    178             (receiver, receiver(signal=self, sender=sender, **named))
--> 179             for receiver in self._live_receivers(sender)
    180         ]
    181

~/venv/noya-TS4FQGPC/lib/python3.7/site-packages/django/dispatch/dispatcher.py in <listcomp>(.0)
    177         return [
    178             (receiver, receiver(signal=self, sender=sender, **named))
--> 179             for receiver in self._live_receivers(sender)
    180         ]
    181

~/venv/noya-TS4FQGPC/lib/python3.7/site-packages/computedfields/handlers.py in postdelete_handler(sender, instance, **kwargs)
    106         with transaction.atomic():
    107             for model, [pks, fields] in updates.items():
--> 108                 active_resolver.bulk_updater(model.objects.filter(pk__in=pks), fields)
    109
    110

~/venv/noya-TS4FQGPC/lib/python3.7/site-packages/computedfields/resolver.py in bulk_updater(self, queryset, update_fields, return_pks, local_only)
    610                 has_changed = False
    611                 for comp_field in mro:
--> 612                     new_value = self._compute(elem, model, comp_field)
    613                     if new_value != getattr(elem, comp_field):
    614                         has_changed = True

~/venv/noya-TS4FQGPC/lib/python3.7/site-packages/computedfields/resolver.py in _compute(self, instance, model, fieldname)
    638         """
    639         field = self._computed_models[model][fieldname]
--> 640         return field._computed['func'](instance)
    641
    642     def compute(self, instance, fieldname):

~/projects/gagosian/noya/gagosian/works/models.py in current_status(self)
    868         if not self.pk:
    869             return ''
--> 870         return self._statuses.first().status_type.description
    871
    872     def get_current_status(self):

AttributeError: 'NoneType' object has no attribute 'status_type'
```

**Comment by jerch** [comment]
@StriveForBest Ah yepp this way the invocation between the deletes actually make sense, and I am not sure if it can be avoided. What happens:
- `WorkStatus` gets deleted --> triggers updates on all related `Work`
- if the last `WorkStatus` was deleted --> `first()` returns `None`, thus an access to the attributes will fail
- eventually `Work` items will also be deleted (depending on cascading rules in place)

Thats abit unfortunate, as it tries to keep `Work` in sync, and would just delete them afterwards. This is a result of the way django has implemented the cascading in python itself. The basic idea behind this behavior is to keep things in sync between two consecutive lines of python code, that alter db state (for model instance code at least, thus you would always see sync values from python side on the same connection object).
If you have an idea how to circumvent this nonsense field updates here, I am all ears.

**Comment by StriveForBest** [comment]
> @StriveForBest Ah yepp this way the invocation between the deletes actually make sense, and I am not sure if it can be avoided. What happens:
> 
>     * `WorkStatus` gets deleted --> triggers updates on all related `Work`
> 
>     * if the last `WorkStatus` was deleted --> `first()` returns `None`, thus an access to the attributes will fail
> 
>     * eventually `Work` items will also be deleted (depending on cascading rules in place)
> 
> 
> Thats abit unfortunate, as it tries to keep `Work` in sync, and would just delete them afterwards. This is a result of the way django has implemented the cascading in python itself. The basic idea behind this behavior of the resolver is to keep things in sync between two consecutive lines of python code, that alter db state (for model instance code at least, thus you would always see sync values from python side on the same connection object).
> If you have an idea how to circumvent this nonsense field updates here, I am all ears.

Yea, that's what I suspected. I think I'll just keep my `.exists()` check for now. I think we can close this issue for now. Thanks for all the help!

**Comment by StriveForBest** [comment]
Hi again @jerch. I think I found a good way to run the `update_dependent` after the migrations:

```python
# works.apps.py

import logging

from django.apps import AppConfig
from django.db import ProgrammingError
from django.db.models.signals import post_migrate


logger = logging.getLogger(__name__)


def compute_denormalized_fields(sender, **kwargs):
    from computedfields.models import update_dependent

    Work = sender.get_model('Work')
    denormalized_fields = (
        'searchable_current_status',
        'searchable_current_price',
    )

    try:
        update_dependent(Work.objects.all(), update_fields=denormalized_fields)
    except ProgrammingError:
        logger.debug(
            f'Denormalized fields ({", ".join(denormalized_fields)}) do not yet exist in database, '
            f'possibly triggered by reverse migration.'
        )


class WorksConfig(AppConfig):
    app_label = 'works'
    name = 'gagosian.works'
    verbose_name = 'Works'

    def ready(self):
        post_migrate.connect(compute_denormalized_fields, sender=self)
```

However `update_dependent` pretty much skips through. I am debugging why and it seems like `Resolver._querysets_for_update` in `computedfields.resolver.py:381` returns an empty dict under variable `final`. I am wondering if you could shine some light on why that might be happening. I also noticed that `update_dependent` has argument `update_local` which is set to `True` by default. Is that relevant?

**Comment by jerch** [comment]
@StriveForBest Are you sure this gets called after all models are properly set up by django? To check that, plz inspect the following attributes on the `active_resolver` (you can import it from models.py or resolver.py):

resolver state flags:
- `_sealed` - should be `True` (indicates, that no new models be registered currently)
- `_initialized` - should be `True` and `_computed_models` should contain all models with computed fields declared
- `_map_loaded` - should be `True` and `_map` should contain the backward resolver map (all models + fields that would update a certain computed field)

**Comment by StriveForBest** [comment]
@jerch see the results:
```python
> /Users/alex.zagoro/projects/gagosian/noya/gagosian/works/apps.py(24)compute_work_denormalized_fields()
     23     import ipdb; ipdb.set_trace()
---> 24     try:
     25         # This doesn't work

ipdb> from computedfields.models import active_resolver
ipdb> active_resolver._sealed
True
ipdb> active_resolver._initialized
True
ipdb> active_resolver._map_loaded
False
```
`self._map` is empty.  But does having 2 out of 3 as `True` help us at all?

Technically, it's not happening within the migrations, it's after the migrations are run. I was under impression that it is outside of migrate process.

The problem with calling a management command is that it will be called on every deploy significantly slowing down the process. And there is no other way to know whether the fields in the db are populated.

**Comment by jerch** [comment]
> How do you guys handle such cases (tests and deploys)?

Well I currently handle that by a custom script, that calls into the affected models with `update_dependent` (pretty much what you did above, but called from outside AFTER the migration). As `updatedata` lacks an interface to do that on the command line, I explicitly set up that script (and have to know when to call it).

The ideal solution would be a neat integration into migrations, with real `post_migrate` support and even `RunPython`. But I am short of knowledge of the migration internals, thus avoided to code that part so far.

**Comment by StriveForBest** [comment]
> > How do you guys handle such cases (tests and deploys)?
> 
> Well I currently handle that by a custom script, that calls into the affected models with `update_dependent` (pretty much what you did above, but called from outside AFTER the migration). As `updatedata` lacks an interface to do that on the command line, I explicitly set up that script (and have to know when to call it).
> 
> The ideal solution would be a neat integration into migrations, with real `post_migrate` support and even `RunPython`. But I am short of knowledge of the migration internals, thus avoided to code that part so far.

Where in the process are you calling it? Would you mind sharing some of what you have?

**Comment by jerch** [comment]
My script basically looks like this:
```python
import django
os.environ['DJANGO_SETTINGS_MODULE'] = '...'
django.setup()

AFFECTED_MODELS = [
    ...
]

for model in AFFECTED_MODELS:
    update_dependent(model.objects.all())
```

You could also shape this into a management command (if you dont like to boostrap django yourself). Might be actually a good idea to expose `update_dependent` more fine-grained than with the big hammer `updatedata`.

**Comment by jerch** [comment]
> Where in the process are you calling it? Would you mind sharing some of what you have?

Woops, for some reason our comments got interleaved. Well you can just call that from your `post_migrate` signal handler, but it is important to call it for a separate process, e.g. with `Popen('python', ['path_to_script']). And it should be the last thing you do in the migration process (to not mess up with db connections and db transactions still pointing to outdated table values).

**Comment by StriveForBest** [comment]
@jerch is there a reason why your management command doesn't call `update_dependent`? It would have been faster than looping through all models and calling `.save()`, wouldn't it?

**Comment by jerch** [comment]
Yes, call this remnants of the past :smile_cat:. The command still dates back, when there was no `update_dependent`at all. Back then everything was bound to `instance.save()` calls.

**Comment by jerch** [comment]
@StriveForBest Wrote an issue for better dealing with migrations, see #65. If you have some insights in migration internals, feel free to share them there.

**Comment by StriveForBest** [comment]
> @StriveForBest Wrote an issue for better dealing with migrations, see #65. If you have some insights in migration internals, feel free to share them there.

I will poke around to see if I have any useful insights :)
You can close this issue at your discretion if you want to track the progress in #65 .
