### ISSUE TITLE
Cloning a model instance thows TypeError

### ISSUE THREAD

**Issue by richarddewit** [netzkolchose/django-computedfields#67]
When cloning a model instance [as mentioned in the Django docs](https://docs.djangoproject.com/en/3.1/topics/db/queries/#copying-model-instances), the following error is raised:

> TypeError: Model instances without primary key value are unhashable

Real world example:

```
Python 3.8.5 (default, Sep  5 2020, 10:50:12) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: i = Invoice.objects.first()

In [2]: i
Out[2]: <Invoice 54dba7e7-6c65-48f8-8665-f2502eeaa5ec>

In [3]: i.pk = None

In [4]: i.save()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-03b5c72fbc4c> in <module>
----> 1 i.save()

~/dev/python/.virtualenvs/invoicerino/lib/python3.8/site-packages/django/db/models/base.py in save(self, force_insert, force_update, using, update_fields)
    751                 update_fields = frozenset(loaded_fields)
    752 
--> 753         self.save_base(using=using, force_insert=force_insert,
    754                        force_update=force_update, update_fields=update_fields)
    755     save.alters_data = True

~/dev/python/.virtualenvs/invoicerino/lib/python3.8/site-packages/django/db/models/base.py in save_base(self, raw, force_insert, force_update, using, update_fields)
    775         meta = cls._meta
    776         if not meta.auto_created:
--> 777             pre_save.send(
    778                 sender=origin, instance=self, raw=raw, using=using,
    779                 update_fields=update_fields,

~/dev/python/.virtualenvs/invoicerino/lib/python3.8/site-packages/django/dispatch/dispatcher.py in send(self, sender, **named)
    175             return []
    176 
--> 177         return [
    178             (receiver, receiver(signal=self, sender=sender, **named))
    179             for receiver in self._live_receivers(sender)

~/dev/python/.virtualenvs/invoicerino/lib/python3.8/site-packages/django/dispatch/dispatcher.py in <listcomp>(.0)
    176 
    177         return [
--> 178             (receiver, receiver(signal=self, sender=sender, **named))
    179             for receiver in self._live_receivers(sender)
    180         ]

~/dev/python/.virtualenvs/invoicerino/lib/python3.8/site-packages/computedfields/handlers.py in get_old_handler(sender, instance, **kwargs)
     61     data = active_resolver.preupdate_dependent(instance, sender)
     62     if data:
---> 63         UPDATE_OLD[instance] = data
     64     return
     65 

~/dev/python/.virtualenvs/invoicerino/lib/python3.8/site-packages/django/db/models/base.py in __hash__(self)
    534     def __hash__(self):
    535         if self.pk is None:
--> 536             raise TypeError("Model instances without primary key value are unhashable")
    537         return hash(self.pk)
    538 

TypeError: Model instances without primary key value are unhashable
```

The culprit is `UPDATE_OLD[instance] = data` in **computedfields/handlers.py**

**Comment by richarddewit** [comment]
A temporary workaround is to reset the model state:

```
Python 3.8.5 (default, Sep  5 2020, 10:50:12) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: i = Invoice.objects.first()

In [2]: i
Out[2]: <Invoice 54dba7e7-6c65-48f8-8665-f2502eeaa5ec>

In [3]: i.pk = None

In [4]: from django.db.models.base import ModelState

In [5]: i._state = ModelState()

In [6]: i.save()

In [7]:
```

**Comment by jerch** [comment]
@richarddewit Thanks for finding this, thats indeed not properly covered atm. The code that fails here is needed to properly update computed fields on reverse fk relations (like aggregates on `fk.to` models). I do a basic check above in the function to exclude newly added instances here: https://github.com/netzkolchose/django-computedfields/blob/06c5e0c8ac6f9945f71c043bcf2405601b62aae5/computedfields/handlers.py#L45-L46

Therefore your workaround can successfully skip the later logic. I am unsure, whether simply skipping here is sufficient or if there are edge cases, that should be updated but are missed. This needs some thinking/testing.

**Comment by jerch** [comment]
@richarddewit

I cannot quite repro the issue with my test models, but that is prolly due to the fact that I dont allow nullable fks and thus have no records with nullish fk fields and the tests wont trigger save here: https://github.com/netzkolchose/django-computedfields/blob/e0491175d60f5b8b0c14997befd7ffcf0e16b985/computedfields/handlers.py#L61-L64

Background on this: `preupdate_dependent` will only return any dirty records for nullable fk fields if the table has records with null in those fields. But it is wrong to update those nullish records here, as the original instance got "copycloned" from a living one with a pk != null, thus should not have been accounted in those null relations in the first place. There is simply no way they could have been accounted under `None|null`, as Django enforces pk being set on db-living objects.


Imho it is safe to add the additional `or not instance.pk` as early exit rule here (see #77).
