### ISSUE TITLE
no field updates after updating to django 3.2

### ISSUE THREAD

**Issue by thht** [netzkolchose/django-computedfields#75]
hi,

sorry to not be able to provide any more in-depth info on this. but i noticed that my fields do not get updated anymore when a dependent field was modified. reverting to django 3.1.8 fixes the issue.

best,
thomas

**Comment by jerch** [comment]
Yeah I already found out that the module is not yet compatible with 3.2. The new version changes some internal aspects of the ORM (a fix is in the works in #72).

**Comment by jerch** [comment]
Fixed with #72 (lands in next release).
