### ISSUE TITLE
Deep fk relations fail to perform as expected

### ISSUE THREAD

**Issue by striveforbest** [netzkolchose/django-computedfields#80]
Here are my models:

```
class Contact(TimeStampedModel, ComputedFieldsModel):
    ...  # not important, it's a reverse lookup down below from Sale


@computed(
        models.BooleanField(default=False, verbose_name='Computed Is Transacting'),
        depends=[
            ['self', ['sales']],
            ['sales', ['invoice']],
            ['sales.invoice', ['status_type']],
        ],
    )
    def computed_is_transacting(self):
        """
        Computed field that is based on whether the Contact is associated to a Work Sale
        (excluding the ones with Invoice.status is Canceled).
        """
        return self.sales.exclude(invoice__isnull=True).exclude(invoice__status_type__title='Cancelled').exists()


class Sale(TimeStampedModel):
    contact = models.ForeignKey('contacts.Contact', models.SET_NULL, blank=True, null=True, related_name='sales')
    invoice = models.ForeignKey('invoices.Invoice', models.SET_NULL, blank=True, null=True, related_name='work_sales')


class Invoice(TimeStampedModel):
    status_type = models.ForeignKey(Invoicestatustype, models.SET_NULL, blank=True, null=True)
```

So, whenever the `Invoice.status_type` changes or `Invoice` instance gets deleted, I need to recalculate my computed field. If sale is added/removed, the same should happen. But it doesn't seem to work. Please advise.

**Comment by jerch** [comment]
Hmm, my first guess here are those SET_NULL constraints, but I have to repro it first. SET_NULL is always a bad choice in terms of relational data integrity, as it basically tells the DB to just forget the relation and keep de-associated entries in the tables.

Furthermore your depends declaration looks wrong to me - `['self', ['sales']]` is an invalid entry (prolly skipped by the resolver), and 'title' of `Invoicestatustype` is the real concrete field altering the CP field value, but it is not declared in depends. Maybe try this one:
```python
[
  ['sales', ['contact']],
  ['sales.invoice.status_type', ['title']]
]
```

**Comment by jerch** [comment]
@striveforbest Did a quick check with this setup:
```python
class Contact(ComputedFieldsModel):
    name = models.CharField(max_length=32)

    @computed(
        models.BooleanField(default=False, verbose_name='Computed Is Transacting'),
        depends=[
            ['sales', ['invoice']],
            ['sales.invoice.status_type', ['status']],
        ],
    )
    def computed_is_transacting(self):
        """
        Computed field that is based on whether the Contact is associated to a Work Sale
        (excluding the ones with Invoice.status is Canceled).
        """
        return self.sales.exclude(invoice__isnull=True).exclude(invoice__status_type__status='B').exists()


class Sale(models.Model):
    contact = models.ForeignKey('Contact', models.SET_NULL, blank=True, null=True, related_name='sales')
    invoice = models.ForeignKey('Invoice', models.SET_NULL, blank=True, null=True, related_name='work_sales')

class Invoicestatustype(models.Model):
    status = models.CharField(max_length=32, choices=[('A', 'A'), ('B', 'B')])

class Invoice(models.Model):
    status_type = models.ForeignKey(Invoicestatustype, models.SET_NULL, blank=True, null=True)
```

This successfully flips `computed_is_transacting` to `True`, if there is at least one invoice with Invoicestatustype.A. It always flips `computed_is_transacting` to `False` on:
- all invoices have Invoicestatustype.B
- no sale attached at all (initial)
- sales got deleted
- invoices got deleted

> I cannot rely on title as it doesn't change. its the association of invoice to status_type that needs to trigger that.

Plz read the docs again. Referring here to `title` will also add the fk relation for updates. (see how I used `['sales.invoice.status_type', ['status']]` above).

So your setup works for me with small adjustments to `depends`.
