### ISSUE TITLE
ComputedFieldsModelMixin

### ISSUE THREAD

**Issue by stygmate** [netzkolchose/django-computedfields#82]
Using ComputedFields with other models class like SingletonModel of Django-Solo is impossible.
Adding the declaration of a ComputedFieldsModelMixin can resolve this issue, allowing us to write:
```python
class MyBestModel(ComputedFieldsModelMixin, SingletonModel):
    pass
```

**Comment by jerch** [comment]
@stygmate Tested it with this dummy setup:
```python
# models.py
from django.db import models
from solo.models import SingletonModel
from computedfields.models import ComputedFieldsModel, computed


class Solo(SingletonModel, ComputedFieldsModel):
    name = models.CharField(max_length=32)

    @computed(models.CharField(max_length=32), depends=[
      ('children', ['name'])
    ])
    def children_name_list(self):
        return ','.join(self.children.all().values_list('name', flat=True))


class Child(ComputedFieldsModel):
    name = models.CharField(max_length=32)
    solo = models.ForeignKey(Solo, related_name='children', on_delete=models.CASCADE)

    @computed(models.CharField(max_length=32, default=''), depends=[
      ('solo', ['name'])
    ])
    def solo_name(self):
        return self.solo.name

# admin.py
from django.contrib import admin
from solo.admin import SingletonModelAdmin

from .models import Solo, Child


class SoloAdmin(SingletonModelAdmin):
    readonly_fields = ('children_name_list',)
    list_display = ('children_name_list',)


class ChildAdmin(admin.ModelAdmin):
    readonly_fields = ('solo_name',)
    list_display = ('name', 'solo_name',)

admin.site.register(Solo, SoloAdmin)
admin.site.register(Child, ChildAdmin)
```

Works in both directions (`Solo` as concrete source for CF on `Child`, `Solo` with CF target). Why is it not working for you?

I see that `SingletonModel` has a cache option to lower db interactions. This ofc will not work with DCF out of the box, as DCF operates on the database. You would have to invalidate the cache entry somehow, which will be possible by a signal from DCF once #58 is done. For now the cache option on a model with `(SingletonModel, ComputedFieldsModel)` inheritance cannot be used, as you would miss the db value changes.

**Comment by jerch** [comment]
@Closing the issue, feel free to reopen if something is still unanswered.
