### ISSUE TITLE
Issues with pre_save signal if update_fields kwargs is not a set

### ISSUE THREAD

**Issue by stephrdev** [netzkolchose/django-computedfields#87]
We're using django-computedfields together with other Django packages. One of them connect a pre_save signal and setting a update_fields keyword argument `update_fields=['order']`.

This leads to an issue right now as computedfields relies on update_fields to be a set (in order to merge the existing update_fields and the own one).

```
  File "/home/steph/.virtualenvs/maapi/lib/python3.8/site-packages/computedfields/handlers.py", line 54, in get_old_handler
    candidates &= kwargs.get('update_fields')
TypeError: unsupported operand type(s) for &=: 'set' and 'list'
```

To quickly solve this in our project I'm now doing something like this:
```
        from computedfields import handlers
        from django.db.models.signals import pre_save

        def get_old_handler(*args, **kwargs):
            if kwargs.get('update_fields'):
                kwargs['update_fields'] = set(kwargs['update_fields'])
            return handlers.get_old_handler(*args, **kwargs)

        pre_save.disconnect(handlers.get_old_handler, sender=None, dispatch_uid='COMP_FIELD_PRESAVE')
        pre_save.connect(get_old_handler, sender=None, weak=False, dispatch_uid='COMP_FIELD_PRESAVE')
```

But I think it could be a good idea to have that fixed in this library too.
I'll try to create a PR by myself soon but if someone wants to jump in thats fine :-)

Besides all that, thanks for building this create library!

**Comment by jerch** [comment]
Ah yepp, looks like a bug to me.

Internally this lib expects `update_fields` to be either `None` or a set like type (django normally emits `frozenset` from signals). Just re-checked the resolver code - yeah, it always casts `updatefields` with `set(updates_fields)`, but I missed it in the handler code (didnt touch that code for quite a while :smile_cat:).

There 6 more code smells in `handler.py` regarding this:
- https://github.com/netzkolchose/django-computedfields/blob/c9adc729888bbd4f7813c852c9bdf2b96d76dc71/computedfields/handlers.py#L160
- https://github.com/netzkolchose/django-computedfields/blob/c9adc729888bbd4f7813c852c9bdf2b96d76dc71/computedfields/handlers.py#L162
- https://github.com/netzkolchose/django-computedfields/blob/c9adc729888bbd4f7813c852c9bdf2b96d76dc71/computedfields/handlers.py#L173
- https://github.com/netzkolchose/django-computedfields/blob/c9adc729888bbd4f7813c852c9bdf2b96d76dc71/computedfields/handlers.py#L175
- https://github.com/netzkolchose/django-computedfields/blob/c9adc729888bbd4f7813c852c9bdf2b96d76dc71/computedfields/handlers.py#L190
- https://github.com/netzkolchose/django-computedfields/blob/c9adc729888bbd4f7813c852c9bdf2b96d76dc71/computedfields/handlers.py#L192

Imho these also should be replaced by `set(left)` or `set(right)` as well.

**Comment by jerch** [comment]
@stephrdev Please see #88 for a fix.
